version: '3.8'
services:
  db-telegram-bot:
    image: postgres
    volumes:
      - C:\studyAndWork\Telegram_Bot\db\postgres\data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - '8082:5432'

  telegram-bot-service:
    image:
      telegram-bot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-telegram-bot:5432/postgres
    ports:
      - '8081:8081'
    depends_on:
      - db-telegram-bot