bot:
  name: Nik_Kon_Bot
  token: 5840825771:AAHLzZBFe_K65WGShlKnjWImp7wZE7ltABM
  owner: 381645544
cron:
  scheduler: 0 * * * * *
spring:
  datasource:
    url: jdbc:postgresql://localhost:8082/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
