bot:
  name: Nik_Kon_Bot
  token: 5840825771:AAHrlpVW1StX0bUI9tx1xvQwt3aUxXkJy4w
  owner: 381645544

spring:
  datasource:
    url: jdbc:postgresql://localhost:8082/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
